### ISSUE TITLE
Search equivalent

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-user-stories#1]
## Value Proposition

**As a** user
**I need** to find a products equivalent from one country to another
**to be able to** use a it

## Description
<img width="450" alt="Search equivalent picture" src="https://user-images.githubusercontent.com/106099037/179200585-0bb0e094-0f41-44bc-98cf-c095036ff978.png">

## Acceptance Criteria

- [ ] Working searchbar
- [ ] Dropdown menu to select both countries
- [ ] Country flags appear after country was selected (2)
- [ ] Working submit button that makes card appear instead of searchbar
- [ ] Each equivalent has its own card
- [ ] Product name on card
- [ ] Product Picture on card
- [ ] Country flag on card
- [ ] Back button exits card and re-opens searchbar

## Tasks

(for developers team)

- [ ] Create db.js with equivalents
- [ ] Searchbar
- [ ] Country drop-down menus (2)
- [ ] Submit button (Mismo!)
- [ ] Back button
- [ ] Equivalent cards
- [ ] Styling
