### ISSUE TITLE
Filter by country

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-user-stories#2]
## Value Proposition

**As a** user
**I need** to filter a product by country
**to be able to** find the equivalent available to me
## Description

<img width="450" alt="Filter issue picture" src="https://user-images.githubusercontent.com/106099037/179222109-8989d8dc-e96b-4a5f-9d43-c36293407f66.png">

## Acceptance Criteria

- [ ] I can select the country I want a products equivalent for by using a drop-down menu
- [ ] I can select the country that I want the equivalent to be from by using a drop-down menu
- [ ] After I selected a country its corresponding flag appears next to it (2)
- [ ] The country flag that I want the equivalent to be from is included on the resulting card

## Tasks

(for developers team)

- [ ] Add the corresponding countries to the existing db.js
- [ ] Country filter function
- [ ] Country drop-down menus (2)
- [ ] Implement the county flag images
- [ ] Styling
- [ ] Write tests

**Comment by yvonneadam** [comment]
It's specific enough and not to overloaded in my eyes, a good one

**Comment by PReichetanz** [comment]
Hi Anna,

this looks really good!
I just have one question: What happens if there is no equivalent product in the country I have chosen? What kind of message will be displayed to the user?
Is this situation possible if you look at your mock data? If so, you should add this here.

**Comment by anresa** [comment]
@PReichetanz That's a great point! I'll adjust my story accordingly. Thank you. ☀️
