### ISSUE TITLE
Add a new equivalent 

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-user-stories#5]
## Value Proposition

**As a** user
**I need** an "add" card/page
**to be able to** add a new equivalent 

## Description

<img width="250" alt="Bildschirmfoto 2022-07-19 um 16 21 35" src="https://user-images.githubusercontent.com/106099037/179774640-299d5f84-99eb-47fc-8496-df96decfd306.png">

## Acceptance Criteria

- [ ] I can type the product name into a text field
- [ ] I can select the country the product is from by using a drop-down menu
- [ ] I can type the equivalent  into a text field
- [ ]  I can select the country the equivalent is from by using a drop-down menu
- [ ]  After I selected a country its corresponding flag appears next to it (2)
- [ ] I can add a picture of my product to the card
- [ ] The new card is being added to the overall databank and can be found over the search function on the homepage
- [ ] I can edit the card later if I want to change something by using the edit button
- [ ] If I don't add a picture, a placeholder default picture is displayed on my card instead

## Tasks

(for developers team)

- [ ] Create "add" card
- [ ] Product text field
- [ ] Equivilant text field
- [ ] Country text field (2)
- [ ] Country drop-down menus (2)
- [ ] Implement the county flag images
- [ ] Add picture function
- [ ] Placeholder picture for pictureless cards
- [ ] Styling
- [ ] Tests
